=== dblencowe/data-dictionary-examples/entity.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="entities">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="entity">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="type"/>
                    <xs:element name="accepted_values">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="item" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="value" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="optional"/>
                  <xs:attribute type="xs:string" name="column" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
            <xs:attribute type="xs:string" name="table"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dblencowe/data-dictionary-examples/mkuser.xml
<?xml version="1.0"?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='entity.xsd'>
    <entity name="User" table="mkuser">
        <attribute name="User Identifier" column="UserPK">
            <type>number</type>
            <accepted_values>[0-9]{1,20}</accepted_values>
        </attribute>
        <attribute name="Username" column="UserID">
            <type>string</type>
            <accepted_values>.*</accepted_values>
        </attribute>
        <attribute name="Account Type" column="UserID">
            <type>enum</type>
            <accepted_values>
                <item value="0">Administrator / Advisor</item>
                <item value="1">Advisor</item>
                <item value="2">Administrator</item>
            </accepted_values>
        </attribute>
    </entity>
</entities>
